encoding: utf-8
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Setup
title: Abdul Ahad
tagline: 'aka Tour Terrible'

url: 'https://tourterrible.github.io/'
baseurl: ''
paginate: 4
permalink: pretty
paginate_path: "/page/:num/"


# About/contact
author:
  name: Abdul Ahad
  url: https://www.instagram.com/__.ahad.___/
theme: minima
plugins:
  - jekyll-paginate

# Sass settings
sass:
  sass_dir: _scss
  style: :compressed
# Custom vars
version: 0.1.0
head: "/public/assets/pic2.jpeg"

exclude:
  - medium-to-markdown*
  - package*
  - node_modules/
  - README.md
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
